apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend  # 'frontend' 라벨을 가진 Pod들 대상으로 트래픽을 전달
  ports:
    - protocol: TCP
      port: 80         # 서비스 외부 포트
      targetPort: 80   # Pod의 포트
  type: LoadBalancer  # 외부에서 접근할 수 있도록 로드밸런서로 설정