apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AWS-Cloud-FinalProject/frontend.git
    targetRevision: doyeon-action
    path: k8s
    helm:
      parameters:
        - name: 'image.repository'
          value: '${ECR_REPOSITORY_URI}'
        - name: 'image.tag'
          value: '${IMAGE_TAG}'
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
