apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 688567288847.dkr.ecr.us-west-2.amazonaws.com/webtest:latest
          ports:
            - containerPort: 80