apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: apps
    meta.helm.sh/release-namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AWS-Cloud-FinalProject/frontend.git
    targetRevision: doyeon-action
    path: helm/frontend
    helm:
      values: |
        image:
          repository: front-test
          tag: v0.0.13
        service:
          type: LoadBalancer
          port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
