apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.service.type | default "LoadBalancer"}}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: frontend 